---
- name: Generate configuration file
  template:
    src: telegraf.conf.j2
    dest: /home/{{remote_user}}/telegraf.conf

- name: Install Docker-Py
  pip:
   name: docker-py
  become: true

- name: Start Telegraf
  docker_container:
    name: telegraf
    image: telegraf:1.3
    state: started
    restart_policy: always
    volumes:
      - "/home/{{remote_user}}/telegraf.conf:/etc/telegraf/telegraf.conf"
